name: Build jdk 11
on:
  push:
    branches:
      - release
      - SIMD-panama
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get -y install maven tree zip

      - name: Applying patch
        run: |
          rm -rf STRACAlign/src/main/java/strac/align/align/implementations/SIMDDTW.java

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '13' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: java -version


      - name: Listing repo
        run : |
          tree .

      - name: Build STRAC
        run: |
          export JAVA_TARGET=11 && mvn clean package -DskipTests

      - name: Compress binaries
        run: |
          zip -r STRACboard-jdk11.zip ./STRACboard/target && zip -r STRACAlign-jdk11.zip ./STRACAlign/target

      - name: Submit release aligners
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: *.zip
          tag: v0.6
          overwrite: true
          file_glob: true
