name: Build jdk panama project
on:
  push:
    branches:
      - release
      # - SIMD-panama
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get -y install tree maven make openjdk-14-jdk libasound2-dev libfontconfig1-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev build-essential zip autoconf mercurial software-properties-common curl


      - name: Java version
        run : |
          export JAVA_HOME=/usr/lib/jvm/java-14-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH && java -version

      - name: Build jdk panama
        run: |
          mkdir panama && cd panama && hg clone http://hg.openjdk.java.net/panama/dev/ && cd dev && bash configure --disable-warnings-as-errors --with-boot-jdk=/opt/jdk-14 && make images

      - name: Build STRAC
        run: |
          ls && cd ../../ && export JAVA_TARGET=15 && mvn clean package -DskipTests

      - name: Compress binaries
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./STRACAlign-jdk15.zip ./STRAC/STRACAlign/target

      - name: Compress binaries dashboard
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./STRACboard-jdk15.zip ./STRAC/STRACboard/target

      - name: Submit release aligners
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./STRACboard-jdk15.zip
          tag: v0.6
          overwrite: true
          file_glob: true

      - name: Submit release board
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./STRACAlign-jdk15.zip
          tag: v0.6
          overwrite: true
          file_glob: true