name: Test STRAC project
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get -y install maven openjdk-14-jdk tree

      - name: Applying patch
        run: |
          rm -rf STRACAlign/src/main/java/strac/align/align/implementations/SIMDDTW.java



      - name: Java version
        run : |
          export JAVA_HOME=/usr/lib/jvm/java-14-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH && java -version

      - name: Listing repo
        run : |
          tree .

      - name: Test STRAC
        run: |
          export JAVA_TARGET=11 && mvn clean test
